```plantuml
@startuml
'https://plantuml.com/sequence-diagram'

autonumber

"Issuer Wallet" -> "Issuer Wallet": Check ODI VC exists
"Issuer Wallet" -> "Issuer Wallet": Create PoA VC Draft and attach\nODI VC using `evidence` field
"Issuer Wallet" <-> "Holder Wallet": Issue PoA via auth or pre-auth interaction

@enduml

```